#!/bin/bash
echo "\033[1;34mINICIANDO A INSTALACAO\033[1;34m"
echo
seleep 4
apt-get update && apt-get upgrade -y
apt-get install curl -y
apt-get install apache2 -y
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
service apache2 restart
apt-get install mysql-server php5-mysql -y
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y
php -m |grep ssh2
service apache2 restart
cd /var/www/html
wget https://raw.githubusercontent.com/Alissongithub/painel3.0/master/painelssh.zip
apt-get install unzip -y
unzip painelssh.zip
rm painelssh.zip index.html
clear
echo "\033[1;34mFINALIZADO COM SUCESSO\033[1;34m"
